version: '3.8'

services:
  rabbitmq-node1:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq-node1
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_DEFAULT_USER: "bianel"
      RABBITMQ_DEFAULT_PASS: "1172459"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
  rabbitmq-node2:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq-node2
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_DEFAULT_USER: "bianel"
      RABBITMQ_DEFAULT_PASS: "1172459"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
